module.exports = (app) => {
    app.get("/content/api/pages/fortnite-game", (req, res) => {
        res.json({
            "jcr:isCheckedOut": true,
            "_title": "Fortnite Game",
            "jcr:baseVersion": "a7ca237317f1e7b00bc82e-d9a2-4f0d-b951-704d295cd1aa",
            "_activeDate": "2017-07-24T22:24:02.300Z",
            "lastModified": "2020-11-01T17:36:19.024Z",
            "_locale": "en-US",
            "emergencynotice": {
                "news": {
                    "platform_messages": [],
                    "_type": "Battle Royale News",
                    "messages": [{
                        "hidden": false,
                        "_type": "CommonUI Simple Message Base",
                        "subgame": "br",
                        "body": "Made by kemo (@xkem0x).\r\nDiscord: https://discord.gg/DJ6VUmD",
                        "title": "Neonite V2",
                        "spotlight": false
                    }, 
                    ],
                },
                "jcr:isCheckedOut": true,
                "_title": "emergencynotice",
                "_noIndex": false,
                "alwaysShow": false,
                "jcr:baseVersion": "a7ca237317f1e761d4ee60-7c40-45a8-aa3e-bb0a2ffa9bb5",
                "_activeDate": "2018-08-06T19:00:26.217Z",
                "lastModified": "2020-10-30T04:50:59.198Z",
                "_locale": "en-US"
            },
            "playlistinformation": {
                "is_tile_hidden": true,
                "frontend_matchmaking_header_style": "None",
                "conversion_config": {
                    "containerName": "playlist_info",
                    "_type": "Conversion Config",
                    "enableReferences": true,
                    "contentName": "playlists"
                },
                "jcr:isCheckedOut": true,
                "show_ad_violator": false,
                "_title": "playlistinformation",
                "frontend_matchmaking_header_text_description": "v2",
                "frontend_matchmaking_header_text": "Neonite",
                "playlist_info": {
                    "_type": "Playlist Information",
                    "playlists": [{
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/partyroyaleupdated/FR_12PR_In-Game_Launch_ModeTile-1024x512-564244d37587a31764a057e113439fbfb60923f3.jpg",
                        "playlist_name": "Playlist_Papaya",
                        "hidden": false,
                        "violator": "",
                        "_type": "FortPlaylistInfo",
                        "description": "Welcome to Neonite\r\n\r\nSorry for french Icon",
                        "display_subname": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-marvelknockout-mystique-ltm-tile-1024x512-969813783.jpg",
                        "playlist_name": "Playlist_Cobalt_HT_Duos",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_subname": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-marvelknockout-wolverine-ltm-tile-1024x512-969818067.jpg",
                        "playlist_name": "Playlist_Cobalt_HT_Trios",
                        "violator": "NOUVEAU",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_subname": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/marvel-standoff-1024x512-010756809.jpg",
                        "playlist_name": "Playlist_hightower",
                        "hidden": false,
                        "violator": "",
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_subname": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/marvel-standoff-1024x512-010756809.jpg",
                        "playlist_name": "Playlist_hightower_12",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_subname": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-marveltakeoverltm-playlisttile-1024x512-1024x512-081336658.jpg",
                        "playlist_name": "Playlist_HighTower_Hydro",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_subname": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-marveltakeoverltm-playlisttile-1024x512-1024x512-081332895.jpg",
                        "playlist_name": "Playlist_HighTower_Hydro_12v12",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_subname": "",
                        "display_name": "Domination Marvel"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-rallyroyaleltm-playlisttile-1024x512-268454418.jpg",
                        "playlist_name": "Playlist_Argon_HighTower_Duos_16",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_subname": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-rallyroyaleltm-playlisttile-1024x512-268454418.jpg",
                        "playlist_name": "Playlist_Argon_HighTower_Solo_16",
                        "hidden": false,
                        "violator": "",
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_subname": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-tiltedtaxi-motd-1024x512-1024x512-890727217.jpg",
                        "playlist_name": "Playlist_Nitrogen12_Trios",
                        "hidden": false,
                        "violator": "",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-tiltedtaxi-motd-1024x512-1024x512-890727217.jpg",
                        "playlist_name": "Playlist_Nitrogen12_Duos",
                        "hidden": false,
                        "violator": "",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-knockoutairraid-motd-1024x512-1024x512-674280089.jpg",
                        "playlist_name": "Playlist_Antares_Squads",
                        "hidden": false,
                        "violator": "",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-tankbattle-motd-1024x512-1024x512-674279961.jpg",
                        "playlist_name": "Playlist_Tank_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-tankbattle-motd-1024x512-1024x512-674279961.jpg",
                        "playlist_name": "Playlist_Tank_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-ragstoriches-motd-1024x512-1024x512-674279937.jpg",
                        "playlist_name": "Playlist_Titanium_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-ragstoriches-motd-1024x512-1024x512-674279937.jpg",
                        "playlist_name": "Playlist_Titanium_Duos",
                        "hidden": false,
                        "violator": "",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-knockoutshuffle-motd-1024x512-1024x512-674280182.jpg",
                        "playlist_name": "Playlist_Mira_Squads",
                        "hidden": false,
                        "violator": "",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-fishingfrenzy-motd-1024x512-1024x512-674279890.jpg",
                        "playlist_name": "Playlist_Polaris_Solo",
                        "hidden": false,
                        "violator": "",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Solid_Gold_Playlist_Tile_1025x512-1024x512-ea1253854e55ed01f3d6e012ecfa373cc1b38d37.jpg",
                        "playlist_name": "Playlist_SolidGold_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-payback-motd-1024x512-1024x512-500823017.jpg",
                        "playlist_name": "Playlist_RespawnPB_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Infiltration_PlaylistTile-1024x512-795e414e6a7e6b050d19c3ef3f226ae0ece00875.jpg",
                        "playlist_name": "Playlist_Infiltration",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Payload_PlaylistTile_1024x512-1024x512-93cd224901b5d4d6585ed1170c700be4b4d2a5cf.png",
                        "playlist_name": "Playlist_Uranium_P",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Cyclone_Astronomical_PlaylistTile_Main-1024x512-ab95f8d30d0742ba1759403320a08e4ea6f0faa0.jpg",
                        "playlist_name": "Playlist_Music_Highest   ",
                        "violator": "ÉVÉNEMENT EN DIRECT",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Atterrissez à Sweaty Sands pour participer à un voyage inoubliable. (Déconseillé aux personnes photosensibles)",
                        "display_name": "Travis Scott Astronomical"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Cyclone_Astronomical_PlaylistTile_Main-1024x512-ab95f8d30d0742ba1759403320a08e4ea6f0faa0.jpg",
                        "playlist_name": "Playlist_Music_Higher",
                        "violator": "ÉVÉNEMENT EN DIRECT",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Atterrissez à Sweaty Sands pour participer à un voyage inoubliable. (Déconseillé aux personnes photosensibles)",
                        "display_name": "Travis Scott Astronomical"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Cyclone_Astronomical_PlaylistTile_Main-1024x512-ab95f8d30d0742ba1759403320a08e4ea6f0faa0.jpg",
                        "playlist_name": "Playlist_Music_High",
                        "violator": "ÉVÉNEMENT EN DIRECT",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Atterrissez à Sweaty Sands pour participer à un voyage inoubliable. (Déconseillé aux personnes photosensibles)",
                        "display_name": "Travis Scott Astronomical"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Cyclone_Astronomical_PlaylistTile_Main-1024x512-ab95f8d30d0742ba1759403320a08e4ea6f0faa0.jpg",
                        "playlist_name": "Playlist_Music_Med",
                        "violator": "ÉVÉNEMENT EN DIRECT",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Atterrissez à Sweaty Sands pour participer à un voyage inoubliable. (Déconseillé aux personnes photosensibles)",
                        "display_name": "Travis Scott Astronomical"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Cyclone_Astronomical_PlaylistTile_PostShow-1024x512-d690fb6ebba8e08fa99102eea12fccc100ed8ece.jpg",
                        "playlist_name": "Playlist_Music_Low",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Rejoignez-nous pour le prochain spectacle Astronomical le 26 avril à 00h00 (CEST).",
                        "display_name": "PROCHAIN ÉVÉNEMENT"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Cyclone_Astronomical_PlaylistTile_Main-1024x512-ab95f8d30d0742ba1759403320a08e4ea6f0faa0.jpg",
                        "playlist_name": "Playlist_Music_Lowest",
                        "violator": "ÉVÉNEMENT EN DIRECT",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Atterrissez à Sweaty Sands pour participer à un voyage inoubliable. (Déconseillé aux personnes photosensibles)",
                        "display_name": "Travis Scott Astronomical"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Knockout_PlaylistTile-1024x512-455f3aa88d1c74b606b17f84852a4c1bbd82eedb.jpg",
                        "playlist_name": "Playlist_Cobalt_Duos_P_Respawn",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Quibi_TheSauce_Nighttime_LTM_1024x512-1024x512-7baf11f7c087e3b74e5a2c3eaf5c2d9cf9f445e4.jpg",
                        "playlist_name": "Playlist_NowPlaying",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Ayo & Teo sont à la recherche de l'équipe la plus stylée. Faites un tour à Risky Reels pour regarder l'émission !",
                        "display_name": "À L'ANTENNE !"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/12BR_Knockout_PlaylistTile-1024x512-455f3aa88d1c74b606b17f84852a4c1bbd82eedb.jpg",
                        "playlist_name": "playlist_cobalt_squads_p_respawn",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/DropZone-1024x512-22ae7474a6c8bdf181e6cee1c546b341b4438fd9.jpg",
                        "playlist_name": "playlist_rumble_op",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/SearchDestroy_Tile_1024x512-1024x512-1e61afa9f8eeced10f55155b9a32530322492138.jpg",
                        "playlist_name": "Playlist_Creative_SourDropper_2",
                        "violator": "CRÉATION DE LA COMMUNAUTÉ",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Opération destruction est un mode temporaire créé par la communauté. \r\nCrique - Créé par : KKSlider \r\n\r\nAssaillants et défenseurs s'affrontent dans ce mode où chaque joueur n'a qu'une vie par manche.  \r\nObjectif des assaillants : poser les bombes sur les sites marqués par A ou B. \r\nObjectif des défenseurs : empêcher les bombes d'être posées et désamorcer celles qui le sont. Au début de chaque manche, les joueurs peuvent dépenser l'or qu'ils ont gagné lors des précédentes manches. L'équipe qui remporte la majorité des manches gagne la partie ! \r\n\r\nSi vous lancez une partie avec moins de 6 joueurs, vous serez placé dans une équipe contenant d'autres joueurs.",
                        "display_subname": "Crique",
                        "display_name": "OPÉRATION DESTRUCTION"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/SearchDestroy_Tile_1024x512-1024x512-1e61afa9f8eeced10f55155b9a32530322492138.jpg",
                        "playlist_name": "Playlist_Creative_SourDropper",
                        "violator": "CRÉATION DE LA COMMUNAUTÉ",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Opération destruction est un mode temporaire créé par la communauté. \r\nUsine - Créé par : DICO \r\n\r\nAssaillants et défenseurs s'affrontent dans ce mode où chaque joueur n'a qu'une vie par manche.  \r\nObjectif des assaillants : poser les bombes sur les sites marqués par A ou B. \r\nObjectif des défenseurs : empêcher les bombes d'être posées et désamorcer celles qui le sont. Au début de chaque manche, les joueurs peuvent dépenser l'or qu'ils ont gagné lors des précédentes manches. L'équipe qui remporte la majorité des manches gagne la partie ! \r\n\r\nSi vous lancez une partie avec moins de 6 joueurs, vous serez placé dans une équipe contenant d'autres joueurs.",
                        "display_subname": "Usine",
                        "display_name": "OPÉRATION DESTRUCTION"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_BattleLabs_PlaylistTile-(2)-1024x512-ca5f4e84a2941264f787239caa5458d0eabd39e3.jpg",
                        "playlist_name": "Playlist_BattleLab_Fortnitemares_MaxFog",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10BR_ZoneWars_In-Game_ModeTile_Blue-1024x512-0f76af6296545de1b2d9da766e76475418bc5940.jpg",
                        "playlist_name": "Playlist_Creative_ZebraWallet_Random",
                        "violator": "CRÉATION DE LA COMMUNAUTÉ",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Guerre de zones en groupe.  Les jeux de type Guerre de zone sont des batailles effrénées jusqu'à la victoire, dans un contexte de tempête se déplaçant rapidement. Les parties se déroulent sur des cartes de petite taille créées par la communauté. Des apparitions et un inventaire aléatoires rendent chaque manche unique. Affrontez 15 autres joueurs, membres de votre groupe y compris.",
                        "display_name": "BATAILLE GÉNÉRALE EN GROUPE"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10BR_ZoneWars_In-Game_ModeTile_Red-1024x512-2e1c5e38b652093029befb6a86a44db844474af8.jpg",
                        "playlist_name": "Playlist_Creative_ZebraWallet_Random2",
                        "violator": "CRÉATION DE LA COMMUNAUTÉ",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Guerre de zones en solo.  Les jeux de type Guerre de zone sont des batailles effrénées jusqu'à la victoire, dans un contexte de tempête se déplaçant rapidement. Les parties se déroulent sur des cartes de petite taille créées par la communauté. Des apparitions et un inventaire aléatoires rendent chaque manche unique. Affrontez 15 autres joueurs aléatoires en solo.",
                        "display_name": "BATAILLE GÉNÉRALE EN SOLO"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-siphon-motd-1024x512-1024x512-501004672.jpg",
                        "playlist_name": "Playlist_Vamp_Duo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_2v2_GunFright_LTM-1024x512-f3b0f0157e8652a23db8abc23814d97893179e20.jpg",
                        "playlist_name": "Playlist_Creative_Hyena_G",
                        "violator": "CRÉATION DE LA COMMUNAUTÉ",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Code BluDrive \r\nCode Axel-Capek \r\n\r\nQuel duo triomphera de cette bataille de champions à deux contre deux ? \r\n\r\nTous les joueurs commencent chaque manche avec le même équipement défini aléatoirement. Le duo qui a remporté le plus de victoires après 5 manches gagne la partie ! \r\n\r\nCartes créées par : BluDrive (Manoir) \r\nAxel-Capek (Cour)"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_LTM_ModeTile-1024x512-aae4d5b5eb1ea4eeb31f852c8b98516681bfe769.jpg",
                        "playlist_name": "Playlist_DADBRO_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_LTM_ModeTile-1024x512-aae4d5b5eb1ea4eeb31f852c8b98516681bfe769.jpg",
                        "playlist_name": "Playlist_DADBRO_Squads_12",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_LTM_ModeTile-1024x512-aae4d5b5eb1ea4eeb31f852c8b98516681bfe769.jpg",
                        "playlist_name": "Playlist_DADBRO_Squads_8",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/FORT_Tile_Tutorial-1024x512-72a618fa185a0bbc26ab6a290bc0a45cf460c576.png",
                        "playlist_name": "Playlist_Tutorial_1",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10BR_ZoneWars_In-Game_ModeTile-1024x512-a2741f113a7178ca15d71d281dcc2b614ff90754.jpg",
                        "playlist_name": "Playlist_Creative_ZebraWallet_A",
                        "violator": "BATAILLE GÉNÉRALE EN GROUPE",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Code jesgran Zone Wars - Arena  Une simulation de fin de partie de Battle Royale en solo, avec une zone mouvante étroite. Éliminez vos adversaires tout en évitant la tempête qui se referme. Des apparitions et un inventaire aléatoires rendent chaque manche unique. Restez après le premier jeu : il y a plusieurs manches à chaque session.  Devenez le gladiateur ultime et régnez sur le Colisée. Cette île de style ouvert requiert une maîtrise de la construction rapide.  Créé par Jesgran.",
                        "display_name": "COLISÉE"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10BR_ZoneWars_In-Game_ModeTile_Red-1024x512-2e1c5e38b652093029befb6a86a44db844474af8.jpg",
                        "playlist_name": "Playlist_Creative_ZebraWallet_D",
                        "violator": "BATAILLE GÉNÉRALE EN SOLO",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Code jotapegame Desert Zone Wars 4.1  Une simulation de fin de partie de Battle Royale en solo, avec une zone mouvante étroite. Éliminez vos adversaires tout en évitant la tempête qui se referme. Des apparitions et un inventaire aléatoires rendent chaque manche unique. Restez après le premier jeu : il y a plusieurs manches à chaque session.  Combattez au milieu d'une petite ville du désert et atteignez le dernier cercle. L'assortiment d'armes et de véhicules variés permet une expérience de jeu originale.  Créé par JotaPeGame.",
                        "display_name": "DÉSERT"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10BR_ZoneWars_In-Game_ModeTile_Blue-1024x512-0f76af6296545de1b2d9da766e76475418bc5940.jpg",
                        "playlist_name": "Playlist_Creative_ZebraWallet_DH",
                        "violator": "BATAILLE GÉNÉRALE EN GROUPE",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Code enigma S10 Enigmas Downhill River Zonewars X  Une simulation de fin de partie de Battle Royale en solo, avec une zone mouvante étroite. Éliminez vos adversaires tout en évitant la tempête qui se referme. Des apparitions et un inventaire aléatoires rendent chaque manche unique. Restez après le premier jeu : il y a plusieurs manches à chaque session.  Dévalez une colline et traversez une rivière tout en restant dans les limites de la tempête ! Les tremplins communautaires et le trajet constant de la tempête permettent de se familiariser avec le jeu en quelques manches.  Créé par Enigma.",
                        "display_name": "RIVIÈRE"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10BR_ZoneWars_In-Game_ModeTile_Black-1024x512-23ba95e82931361ce535a643fdac54e120254374.jpg",
                        "playlist_name": "Playlist_Creative_ZebraWallet_V",
                        "violator": "BATAILLE GÉNÉRALE EN GROUPE",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Code zeroyahero Vortex Zone Wars by Zeroyahero  Une simulation de fin de partie de Battle Royale en solo, avec une zone mouvante étroite. Éliminez vos adversaires tout en évitant la tempête qui se referme. Des apparitions et un inventaire aléatoires rendent chaque manche unique. Restez après le premier jeu : il y a plusieurs manches à chaque session.  La petite originalité de cette Guerre de zones est son terrain montagneux : l'altitude peut varier énormément d'une zone à l'autre !  Créé par Zeroyahero.",
                        "display_name": "VORTEX"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10BR_TheCombine_ModeTile-1024x512-3aa8ebdfe1df7d9995e824a781eacdb954ee9615.jpg",
                        "playlist_name": "Playlist_Crucible_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": "Le Creuset"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/BR_LTM-Tile_Playground-1024x512-53db8a4b5fb41251af279eaf923bc00ecbc17792.jpg",
                        "playlist_name": "Playlist_Creative_PlayOnly_40",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10CM_LTM_KnockTown_Playlist-1024x512-72e32b88b332b4d3ee3ee5255eff9522b660485c.jpg",
                        "playlist_name": "Playlist_Creative_KaleTofu",
                        "violator": "CRÉATION DE LA COMMUNAUTÉ",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Bounty_LTM_V2_Playlist_Tile-1024x512-3528a95d869a442d61687b52253a56a36c92eea3.jpg",
                        "playlist_name": "Playlist_Bounty_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Bounty_LTM_V2_Playlist_Tile-1024x512-3528a95d869a442d61687b52253a56a36c92eea3.jpg",
                        "playlist_name": "Playlist_Bounty_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Bounty_LTM_V2_Playlist_Tile-1024x512-3528a95d869a442d61687b52253a56a36c92eea3.jpg",
                        "playlist_name": "Playlist_Bounty_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/09CM_WorldCup_FeatIsland_WorldRun_ModeTile-1024x512-34d66c90603f4e64ebd56054b889c4ec163abea5.jpg",
                        "playlist_name": "Playlist_Creative_Squad_Battle_16_B",
                        "violator": "CRÉATION DE LA COMMUNAUTÉ",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_SneakySilencers-1024x512-1669e2eeddca63b61e9b94cc19c3ec502fd33f29.jpg",
                        "playlist_name": "Playlist_Sneaky_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/09CM_WorldCup_FeatIsland_JunkyardJuke_ModeTile-1024x512-7a2585ce248f1efa438674c368b37116dc5514de.jpg",
                        "playlist_name": "Playlist_Creative_Squad_Battle_16_A",
                        "violator": "CRÉATION DE LA COMMUNAUTÉ",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/09CM_WorldCup_FeatIsland_SkyStation_ModeTile-1024x512-a5424f9ac27626a73646c9fd158901c4c363ec0c.jpg",
                        "playlist_name": "Playlist_Creative_Squad_Battle_32_A",
                        "violator": "CRÉATION DE LA COMMUNAUTÉ",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Conçu par Team Evolve. Présenté lors de la finale de la Fortnite World Cup - Mode Créatif.  Affrontez les autres sections pour capturer des zones et gagner des points ! Tous les joueurs peuvent capturer une zone et gagner des points pour leur équipe. Utilisez des grenades répulsives pour chasser les autres équipes des zones de capture ! Les joueurs peuvent désormais gagner de l'EXP après chaque partie et les trois meilleures équipes gagnent de l'EXP bonus."
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-oneshot-motd-1024x512-1024x512-347318026.jpg",
                        "playlist_name": "Playlist_Low_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_HeavyMetal_ModeTile-1024x512-4db8223707fb313220eef577dafde5c14106e49d.jpg",
                        "playlist_name": "Playlist_Heavy_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/09CM_In-Game_PropHunt_ModeTile-1024x512-1510311027a93a720b42ed22e711c7e478931adb.jpg",
                        "playlist_name": "Playlist_Creative_PuppyHugs",
                        "violator": "CRÉÉ PAR DES JOUEURS",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Unvaulted-1024x512-d3cbe3c4a756190279af4ce98773d6599f7aab4f.jpg",
                        "playlist_name": "Playlist_Unvaulted_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/EN_CM09_BeachAssaultCreativeLTM_ContestWinner_ModeTile-1024x512-9cdeb2e0ea37179a37d3384cf73c9949d2d19546.jpg",
                        "playlist_name": "Playlist_Creative_BeachAssault",
                        "violator": "CRÉÉ PAR DES JOUEURS",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": "Assaut sur la plage, par Prudiz"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Barebones-1024x512-4a29337febb04e9043d57c9e61afe849f8a9e9c7.jpg",
                        "playlist_name": "Playlist_Hard_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Dans ce mode, la carte, la boussole, les comptes à rebours et de nombreux autres éléments d'interface sont désactivés."
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_BlueWeapons_ModeTile-1024x512-0c38f1bc3b991943e3f6650bf7acfbcdd8739b1e.jpg",
                        "playlist_name": "Playlist_Blue_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Toutes les armes sont de rareté bleue !",
                        "display_name": "Peur bleue"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Solid_Gold_Playlist_Tile_1025x512-1024x512-ea1253854e55ed01f3d6e012ecfa373cc1b38d37.jpg",
                        "playlist_name": "Playlist_SolidGold_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Toutes les armes sont légendaires !",
                        "display_name": "Or massif"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_PurpleReign_ModeTile-1024x512-c5a7e2bd3f32b83f17e4fa28817312ab6210133c.jpg",
                        "playlist_name": "Playlist_Purple_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_FullAuto_ModeTile-1024x512-d1532221d738ba3aed434512b7c670e72b89f474.jpg",
                        "playlist_name": "Playlist_Auto_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_HeavyMetal_ModeTile-1024x512-4db8223707fb313220eef577dafde5c14106e49d.jpg",
                        "playlist_name": "Playlist_Heavy_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-gungame-motd-1024x512-1024x512-501005598.jpg",
                        "playlist_name": "Playlist_Gungame_Reverse",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_Surfin_ModeTile-1024x512-ebff23e30b121cfe3eecf173949c055325522090.jpg",
                        "playlist_name": "Playlist_Race_12",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_DeaglesandHeadshots_ModeTile-1024x512-4d969f5a9126ba71b7ee77088fd22df5b4c7caba.jpg",
                        "playlist_name": "Playlist_Beagles_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_LeaveNoneBehind_ModeTile-1024x512-bfe65d02a5d42577d22c133d25ad9c9fb62a35a0.jpg",
                        "playlist_name": "Playlist_Behind_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_LoadoutSwap_ModeTile-1024x512-f73c146f8ccc7998aab14f8c1957f0ad01faa933.jpg",
                        "playlist_name": "Playlist_Swap_Squads_Respawn",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_TankBattle_ModeTile-1024x512-48554aae511d9c5a7ac1a5d4fd54e0f5a37bd66d.jpg",
                        "playlist_name": "Playlist_Tank_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_StrategicStructures_ModeTile-1024x512-4f6f448375284fef60fe2a2c15f292115ebec558.jpg",
                        "playlist_name": "Playlist_Strategic_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_BuildersParadise_ModeTile-1024x512-730a5ffe51c8f0420b91529d1fc05e081aa2071c.jpg",
                        "playlist_name": "Playlist_Paradise_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_PowerUp_ModeTile-1024x512-7e1824071133f9eac4ca44c701605923893c85bf.jpg",
                        "playlist_name": "Playlist_Pow_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_BuilttoLast_ModeTile-1024x512-cf95f4701f41c608ae8590fe588a5a0ea25ed68a.jpg",
                        "playlist_name": "Playlist_Care_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_Tag_ModeTile-1024x512-d4471981ccdc8d9f444d1f416b3f4458612da006.jpg",
                        "playlist_name": "Playlist_Tag_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_WaterBalloons_ModeTile-1024x512-ea418e1a4fb6ce21d5f01f2ac18ae60e41e9ef74.jpg",
                        "playlist_name": "Playlist_Bison_Respawn_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Deux équipes de grande taille s'affrontent avec des ballons remplis d'eau pour décrocher la Victoire royale dans ce mode bourré d'action où le premier camp à atteindre l'objectif d'éliminations l'emporte !"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_WaterBalloons_ModeTile-1024x512-ea418e1a4fb6ce21d5f01f2ac18ae60e41e9ef74.jpg",
                        "playlist_name": "Playlist_Bison_Respawn",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Deux équipes de grande taille s'affrontent avec des ballons remplis d'eau pour décrocher la Victoire royale dans ce mode bourré d'action où le premier camp à atteindre l'objectif d'éliminations l'emporte !"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_SiphonRumble_ModeTile-1024x512-02ad3c97e4cdc7172f6ea59140b89b004f95886a.jpg",
                        "playlist_name": "Playlist_Respawn_20_Sif",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_LavaRumble_ModeTile-1024x512-29cc6ad680519d8f792bf1fa4053cf9191f84b6e.jpg",
                        "playlist_name": "Playlist_Respawn_20_Lava",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-payback-motd-1024x512-1024x512-500823017.jpg",
                        "playlist_name": "Playlist_Respawn_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/09BR_LTM_HordeRush_Mode_Tile-1024x512-a844840eb58db868b6abfbe18fc8a8f483e18c60.jpg",
                        "playlist_name": "Playlist_Mash_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/09BR_LTM_DowntownDrop_Screenshot_ModeTile-1024x512-d8ce0a16ae59e2a2f501813ddf540a00e60098b5.jpg",
                        "playlist_name": "Playlist_Creative_Vigilante",
                        "violator": "PLAYER MADE!",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Created by NotNellaf & Tollmolia in collaboration with Jordan Brand. \r\n\r\nShow off your moves in the Downtown Drop LTM. Launch off massive jumps, grind down city streets and collect coins to win! \r\n\r\nProve you deserve the title of G.O.A.T."
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/09BR_Social_LTM_WicksBounty_Announce_PlaylistTile-1024x512-df3870c355530a7591c7a3fa453c15686c862989.jpg",
                        "playlist_name": "Playlist_Wax_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/09BR_Social_LTM_WicksBounty_Announce_PlaylistTile-1024x512-df3870c355530a7591c7a3fa453c15686c862989.jpg",
                        "playlist_name": "Playlist_Wax_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/09BR_Social_LTM_WicksBounty_Announce_PlaylistTile-1024x512-df3870c355530a7591c7a3fa453c15686c862989.jpg",
                        "playlist_name": "Playlist_Wax_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_Endgame_InGame_Mode-Tile-1024x512-03bb0dc121ae8b2dcd27b8b386670737093d0c83.jpg",
                        "playlist_name": "Playlist_Ashton_Sm",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/EN_08BR_DeepFried_Mode_Tile-1024x512-227979fa27053f858066a1a47d68b55f792fded1.jpg",
                        "playlist_name": "Playlist_Barrier_16_B_Lava",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_AirRoyale_Mode-Tile-1024x512-e071f542b7e0ce2cfc34c208e14604815b76439c.jpg",
                        "playlist_name": "Playlist_Goose_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_AirRoyale_Mode-Tile-1024x512-e071f542b7e0ce2cfc34c208e14604815b76439c.jpg",
                        "playlist_name": "Playlist_Goose_Duos_24",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_AirRoyale_Mode-Tile-1024x512-e071f542b7e0ce2cfc34c208e14604815b76439c.jpg",
                        "playlist_name": "Playlist_Goose_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/CM_LobbyTileArt-1024x512-fbcd48db36552ccb1ab4021b722ea29d515377cc.jpg",
                        "playlist_name": "Playlist_PlaygroundV2",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Jouez aux meilleures créations de la communauté. Il y a une nouvelle île à la Une chaque jour dans le mode Créatif !"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_FloorIsLava_ModeTile-1024x512-f1af4cd98c7ff0ce4058f4e3b65a853641d0a35e.jpg",
                        "playlist_name": "Playlist_Fill_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_FloorIsLava_ModeTile-1024x512-f1af4cd98c7ff0ce4058f4e3b65a853641d0a35e.jpg",
                        "playlist_name": "Playlist_Fill_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_FloorIsLava_ModeTile-1024x512-f1af4cd98c7ff0ce4058f4e3b65a853641d0a35e.jpg",
                        "playlist_name": "Playlist_Fill_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_SolidGreen_ModeTile_Squads-1024x512-f0d931472907d54ffaa52ef81f78bf9d5fcfaa2d.jpg",
                        "playlist_name": "Playlist_Green_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_SolidGreen_ModeTile_Squads-1024x512-f0d931472907d54ffaa52ef81f78bf9d5fcfaa2d.jpg",
                        "playlist_name": "Playlist_Green_Squad",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_SolidGreen_ModeTile_Squads-1024x512-f0d931472907d54ffaa52ef81f78bf9d5fcfaa2d.jpg",
                        "playlist_name": "Playlist_Green_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_WinterFest_Social_Slide_LTM_MOTD_1024x512-1024x512-e568425bdc8ac88c7cea6a277d0cf3f081563541.jpg",
                        "playlist_name": "Playlist_Slide_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Unvaulted-1024x512-d3cbe3c4a756190279af4ce98773d6599f7aab4f.jpg",
                        "playlist_name": "Playlist_Classic_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_Drifting50s_Powder-1024x512-5fb24cfd4d83e4cd3a3589b126313beba9cc69a7.jpg",
                        "playlist_name": "Playlist_Hover",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_Drifting50s_Powder-1024x512-5fb24cfd4d83e4cd3a3589b126313beba9cc69a7.jpg",
                        "playlist_name": "Playlist_Hover_64",
                        "violator": "Large Team Mode",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_Drifting50s_Powder-1024x512-5fb24cfd4d83e4cd3a3589b126313beba9cc69a7.jpg",
                        "playlist_name": "Playlist_Hover_48",
                        "violator": "Large Team Mode",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_InfinityBlade_v2-1024x512-475608c25c288f7d5c884eeebc47fb565f6f5803.jpg",
                        "playlist_name": "Playlist_Sword_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_InfinityBlade_v2-1024x512-475608c25c288f7d5c884eeebc47fb565f6f5803.jpg",
                        "playlist_name": "Playlist_Sword_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_InfinityBlade_v2-1024x512-475608c25c288f7d5c884eeebc47fb565f6f5803.jpg",
                        "playlist_name": "Playlist_Sword_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_LoveShot_v2-1024x512-cd7b917157be2472bebc3db3b125e9b20174c748.jpg",
                        "playlist_name": "Playlist_Love_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_LoveShot_v2-1024x512-cd7b917157be2472bebc3db3b125e9b20174c748.jpg",
                        "playlist_name": "Playlist_Love_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_LoveShot_v2-1024x512-cd7b917157be2472bebc3db3b125e9b20174c748.jpg",
                        "playlist_name": "Playlist_Love_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Catch_LTM_ModeTile_1024x512-1024x512-c082fbf692a53d713da02592e9de69faeefd587c.jpg",
                        "playlist_name": "Playlist_Toss_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_CatchSquads-1024x512-7289222d56b08ef8de20c7187af2670496dca3df.jpg",
                        "playlist_name": "Playlist_Toss_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-catch-motd-1024x512-1024x512-500636478.jpg",
                        "playlist_name": "Playlist_Toss_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_NFL_Playlist_Tile-1024x512-767f5e54a71ef1c9fbd4bfdb8c8ec3b15aac8a5e.jpg",
                        "playlist_name": "Playlist_Omaha",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_WinterDeimos_Squads-1024x512-cf4323aa9c2cfd027484cf4da14544128e3d4c7e.jpg",
                        "playlist_name": "Playlist_Deimos_Squad_Winter",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_WinterDeimos_Duos_-1024x512-84315aac8d1fcfb840deba46c4dafda8e9005b2a.jpg",
                        "playlist_name": "Playlist_Deimos_Duo_Winter",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_WinterDeimos_Solo-1024x512-5c759fe60ec85988f35c729b5fb6a7993d8dbb58.jpg",
                        "playlist_name": "Playlist_Deimos_Solo_Winter",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-oneshot-motd-1024x512-1024x512-347318026.jpg",
                        "playlist_name": "Playlist_Low_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_GroundGame-1024x512-37a4d1d335b4c9427bdc672db0f335f4df813874.jpg",
                        "playlist_name": "Playlist_Ground_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_WildWest-1024x512-42779242a5a73d654332d9d0afe0983f9d8401d0.jpg",
                        "playlist_name": "Playlist_WW_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Slide-1024x512-189625349e80dc81e225691aa952ffd280996058.jpg",
                        "playlist_name": "Playlist_Slide_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_GroundGame-1024x512-37a4d1d335b4c9427bdc672db0f335f4df813874.jpg",
                        "playlist_name": "Playlist_Ground_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_GroundGame-1024x512-37a4d1d335b4c9427bdc672db0f335f4df813874.jpg",
                        "playlist_name": "Ground_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-oneshot-motd-1024x512-1024x512-347318026.jpg",
                        "playlist_name": "Playlist_Low_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_HighExplosives50s-1024x512-3a8d44af3c2718b5aaaaebbd4627258a657bf0bf.jpg",
                        "playlist_name": "Playlist_50v50HE",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_HighExplosives-1024x512-4afc4219531db710e56f3b038e7cd84ca2be7675.jpg",
                        "playlist_name": "Playlist_HighExplosives_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_HighExplosives-1024x512-4afc4219531db710e56f3b038e7cd84ca2be7675.jpg",
                        "playlist_name": "Playlist_HighExplosives_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_HighExplosives-1024x512-4afc4219531db710e56f3b038e7cd84ca2be7675.jpg",
                        "playlist_name": "Playlist_HighExplosives_Squads / Event 24",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_WildWest-1024x512-42779242a5a73d654332d9d0afe0983f9d8401d0.jpg",
                        "playlist_name": "Playlist_WW_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_SneakySilencers-1024x512-1669e2eeddca63b61e9b94cc19c3ec502fd33f29.jpg",
                        "playlist_name": "Playlist_Sneaky_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_FoodFight16-1024x512-309538a1b961b5ab0c22417ab34170cc302bbab8.jpg",
                        "playlist_name": "Playlist_Barrier_16",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_CloseEncounters50s-1024x512-03dcc058e1bec3e853b3ee20594128805223b5a3.jpg",
                        "playlist_name": "Playlist_Close_50",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_HolidayDisco-1024x512-684bd4b41613e59d895a477389515a8b4878da6a.jpg",
                        "playlist_name": "Playlist_Disco_32_Alt",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Slide-1024x512-189625349e80dc81e225691aa952ffd280996058.jpg",
                        "playlist_name": "Playlist_Slide_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Barebones-1024x512-4a29337febb04e9043d57c9e61afe849f8a9e9c7.jpg",
                        "playlist_name": "Playlist_Hard_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-siphon-motd-1024x512-1024x512-501004672.jpg",
                        "playlist_name": "Playlist_Vamp_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_14-DoF_Social-1024x512-5fa7dd4752d1f0cc1a101f09cb170d0f5b2a31cf.jpg",
                        "playlist_name": "Playlist_33",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Unvaulted-1024x512-d3cbe3c4a756190279af4ce98773d6599f7aab4f.jpg",
                        "playlist_name": "Playlist_Unvaulted_Squads",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/team-rumble-1024x512-534456830.jpg",
                        "playlist_name": "Playlist_Respawn_24",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_ModeTile_LTM_WildWest-1024x512-f67d9d1dd2ca0b290c92b1380240429f0f257a10.jpg",
                        "playlist_name": "Playlist_WW_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_LobbyTile_FoodFight-1024x512-5e1540a0a2ba0a1f663d32c60cfec3a360278672.png",
                        "playlist_name": "Playlist_Barrier_12",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_In-GamePlaylist_TeamTerror-1024x512-310430bdaf1b1dd0ecb4d3b180bb6409b7ff6e27.jpg",
                        "playlist_name": "playlist_deimos_50",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_Fortnitemares_In-GamePlaylist_1024x512_-Solo-1024x512-7e7fe76e48beb3a06da0592cb26e412265986e4d.jpg",
                        "playlist_name": "Playlist_Deimos_Solo",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_Fortnitemares_In-GamePlaylist_1024x512_Squads-1024x512-783a0812f6acf1f5931c8015e6ad13c0b76c5a9c.jpg",
                        "playlist_name": "Playlist_Deimos_Squad",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_Fortnitemares_In-GamePlaylist_1024x512_Duos-1024x512-1eadb7cfab62c9eb5c90c65577c676d5d0bb15c2.jpg",
                        "playlist_name": "Playlist_Deimos_Duo",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_LobbyTile_LTM_DiscoDomination-1024x512-c79f07de78d8283656fcf4d1ee757f880911d775.jpg",
                        "playlist_name": "Playlist_Disco_32",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_LobbyTile_LTM_DiscoDomination-1024x512-c79f07de78d8283656fcf4d1ee757f880911d775.jpg",
                        "playlist_name": "Playlist_Disco",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_Soaring50s-1024x512-80762dcc260cc959c11dac2ca2f6ae176eb63ef3.jpg",
                        "playlist_name": "Playlist_Soaring_Squads",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_Soaring50s-1024x512-80762dcc260cc959c11dac2ca2f6ae176eb63ef3.jpg",
                        "playlist_name": "Playlist_Soaring_Duos",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_Soaring50s-1024x512-80762dcc260cc959c11dac2ca2f6ae176eb63ef3.jpg",
                        "playlist_name": "Playlist_Soaring_Solo",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_HighStakes_ModeTile-1024x512-741e576e8ae2e30c256ff3508011760ace890711.jpg",
                        "playlist_name": "Playlist_Bling_Squads",
                        "violator": "",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_HighStakes_ModeTile-1024x512-741e576e8ae2e30c256ff3508011760ace890711.jpg",
                        "playlist_name": "Playlist_Bling_Duos",
                        "violator": "",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo",
                        "description": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_HighStakes_ModeTile-1024x512-741e576e8ae2e30c256ff3508011760ace890711.jpg",
                        "playlist_name": "Playlist_Bling_Solo",
                        "violator": "",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Solid_Gold_Playlist_Tile_1025x512-1024x512-ea1253854e55ed01f3d6e012ecfa373cc1b38d37.jpg",
                        "playlist_name": "Playlist_50v50SAU",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM_ScoreRoyale-1024x512-b608aaf7840cdf6b7a702c5cbe1848a2247516d6.jpg",
                        "playlist_name": "Playlist_Score_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM_ScoreRoyale-1024x512-b608aaf7840cdf6b7a702c5cbe1848a2247516d6.jpg",
                        "playlist_name": "Playlist_Score_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM_ScoreRoyale-1024x512-b608aaf7840cdf6b7a702c5cbe1848a2247516d6.jpg",
                        "playlist_name": "Playlist_Score_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_Soaring50s-1024x512-80762dcc260cc959c11dac2ca2f6ae176eb63ef3.jpg",
                        "playlist_name": "Playlist_Soaring_50s",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM-Steady-Storm-1024x512-f38e603ed9c80b6210a25c4737d3d8b675b8d28e.jpg",
                        "playlist_name": "Playlist_Steady_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM-Steady-Storm-1024x512-f38e603ed9c80b6210a25c4737d3d8b675b8d28e.jpg",
                        "playlist_name": "Playlist_Steady_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM-Steady-Storm-1024x512-f38e603ed9c80b6210a25c4737d3d8b675b8d28e.jpg",
                        "playlist_name": "Playlist_Steady_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_FlyExplosives-1024x512-6283e3392b3aa44794dac64423b22606f8773503.png",
                        "playlist_name": "Playlist_FlyExplosives_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_FlyExplosives-1024x512-6283e3392b3aa44794dac64423b22606f8773503.png",
                        "playlist_name": "Playlist_FlyExplosives_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_FlyExplosives-1024x512-6283e3392b3aa44794dac64423b22606f8773503.png",
                        "playlist_name": "Playlist_FlyExplosives_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/LTM_Tile_FinalFight-1024x576-5af82788940faeef422ad204aaa241e36e7c9c56.jpg",
                        "playlist_name": "Playlist_Final_12",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/BR_LTM-Tile_Playground-1024x512-53db8a4b5fb41251af279eaf923bc00ecbc17792.jpg",
                        "playlist_name": "Playlist_Creative_PlayOnly",
                        "violator": "",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo",
                        "display_subname": "-"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistimages/BR_LTM-Tile_Tactics-Showdown-1024x512-a84753f49eb70d8751a99b4db83cdb5eb8290166.jpg",
                        "playlist_name": "Playlist_Taxes_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistimages/BR_LTM-Tile_Tactics-Showdown-1024x512-a84753f49eb70d8751a99b4db83cdb5eb8290166.jpg",
                        "playlist_name": "Playlist_Taxes_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistimages/BR_LTM-Tile_Tactics-Showdown-1024x512-a84753f49eb70d8751a99b4db83cdb5eb8290166.jpg",
                        "playlist_name": "Playlist_Taxes_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/LTM_Tile_FinalFight-1024x576-5af82788940faeef422ad204aaa241e36e7c9c56.jpg",
                        "playlist_name": "Playlist_Final_20",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR04_LTM_SniperShootout-1024x512-bcaf8004961e4e374d0603813f840f4b575d230b.jpg",
                        "playlist_name": "Playlist_Snipers_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR04_LTM_SniperShootout-1024x512-bcaf8004961e4e374d0603813f840f4b575d230b.jpg",
                        "playlist_name": "Playlist_Snipers_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR04_LTM_SniperShootout-1024x512-bcaf8004961e4e374d0603813f840f4b575d230b.jpg",
                        "playlist_name": "Playlist_Snipers_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/BR04_LTM_BlitzShowdown-1024x512-7eccbc505214ac522cc5dde7b3ceaa3a5f99e754.png",
                        "playlist_name": "Playlist_Comp_Blitz_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR04_LTM_5x20-1024x512-451b402db5751c25a1e7616930c5ae37d8b20710.png",
                        "playlist_name": "Playlist_5x20",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_In-Game_LTM_Blitz_Masked_ModeTile-1024x512-ca1788d0b956e789da358481747272e1bb64c710.jpg",
                        "playlist_name": "Playlist_Blitz_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_In-Game_LTM_Blitz_Masked_ModeTile-1024x512-ca1788d0b956e789da358481747272e1bb64c710.jpg",
                        "playlist_name": "Playlist_Blitz_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_In-Game_LTM_Blitz_Masked_ModeTile-1024x512-ca1788d0b956e789da358481747272e1bb64c710.jpg",
                        "playlist_name": "Playlist_Blitz_Squad",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Close_EncountersMOTD_1024x512-1024x512-b8ae46224a1de0d4db833c23755f4afabffb34b9.jpg",
                        "playlist_name": "Playlist_Close_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Close_EncountersMOTD_1024x512-1024x512-b8ae46224a1de0d4db833c23755f4afabffb34b9.jpg",
                        "playlist_name": "Playlist_Close_Squad",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Close_EncountersMOTD_1024x512-1024x512-b8ae46224a1de0d4db833c23755f4afabffb34b9.jpg",
                        "playlist_name": "Playlist_Close_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/BR04_LTM_SoloShowdown-1024x512-0f522b0881adebfe241c6527f03c9140f70b88a7.png",
                        "playlist_name": "Playlist_Comp_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Solid_Gold_Playlist_Tile_1025x512-1024x512-ea1253854e55ed01f3d6e012ecfa373cc1b38d37.jpg",
                        "playlist_name": "Playlist_SolidGold_Solo",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Close_EncountersMOTD_1024x512-1024x512-b8ae46224a1de0d4db833c23755f4afabffb34b9.jpg",
                        "playlist_name": "Playlist_Close_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/LTM_50v50-1024x512-788bf1a67426f54307c4296123ac2d3ff8cc0d6c.png",
                        "playlist_name": "Playlist_50v50",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR04_LTM_Gauntlet-1024x512-a0dca279534a121957275bcdb0b42042d8a010fd.png",
                        "playlist_name": "Playlist_Carmine",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-launch-modetiles-solo-1024x512-850175411.jpg",
                        "playlist_name": "Playlist_DefaultSolo",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-launch-modetiles-duos-1024x512-850175511.jpg",
                        "playlist_name": "Playlist_DefaultDuo",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-launch-modetiles-trios-1024x512-850175437.jpg",
                        "playlist_name": "playlist_trios",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-fortnitemares-solo-1024x512-326832464.jpg",
                        "playlist_name": "Playlist_Arseniccore_Solo_Maxfog",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-launch-modetiles-squad-1024x512-850175426.jpg",
                        "playlist_name": "Playlist_DefaultSquad",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-fortnitemares-duos-1024x512-326842571.jpg",
                        "playlist_name": "Playlist_Arseniccore_Duos_Maxfog",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-fortnitemares-trios-1024x512-326846465.jpg",
                        "playlist_name": "playlist_arseniccore_trios_maxfog",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-fortnitemares-squad-1024x512-326850231.jpg",
                        "playlist_name": "playlist_arseniccore_squads_maxfog",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }]
                },
                "_noIndex": false,
                "jcr:baseVersion": "a7ca237317f1e75e69721b-e10f-4b06-bd20-3a713b3b27e5",
                "_activeDate": "2018-04-25T15:05:39.956Z",
                "lastModified": "2020-10-14T14:18:18.578Z",
                "_locale": "en-US"
            },
            "dynamicbackgrounds": {
                "jcr:isCheckedOut": true,
                "backgrounds": {
                    "backgrounds": [{
                        "stage": "season14",
                        "_type": "DynamicBackground",
                        "key": "lobby"
                    }, {
                        "stage": "default",
                        "_type": "DynamicBackground",
                        "key": "vault"
                    }],
                    "_type": "DynamicBackgroundList"
                },
                "_title": "dynamicbackgrounds",
                "_noIndex": false,
                "jcr:baseVersion": "a7ca237317f1e7bac3355e-3ec1-4054-baf5-f88613799961",
                "_activeDate": "2019-08-21T15:59:59.342Z",
                "lastModified": "2020-08-27T08:04:47.051Z",
                "_locale": "en-US"
            },
            "battleroyalenewsv2": {
                "news": {
                    "motds": [{
                        "entryType": "Website",
                        "image": "https://cdn.discordapp.com/attachments/703974059121049720/715300713995042877/Fornite1920x1080.jpg",
                        "tileImage": "https://cdn.discordapp.com/attachments/703974059121049720/715300717837156362/FortniteMidLogo.jpg",
                        "videoMute": false,
                        "hidden": false,
                        "tabTitleOverride": "Neonite V2",
                        "_type": "CommonUI Simple Message MOTD",
                        "title": "Neonite",
                        "body": "Made by Kemo (@xkem0x). If you have any bugs, you can join our Discord by clicking the button below.",
                        "videoLoop": false,
                        "videoStreamingEnabled": false,
                        "sortingPriority": 80,
                        "id": "NeoniteNewsBR",
                        "videoAutoplay": false,
                        "videoFullscreen": false,
                        "spotlight": false,
                        "websiteURL": "https://discord.gg/DJ6VUmD",
                        "websiteButtonText" : "Join our discord"
                    }
                ],
                },
                "jcr:isCheckedOut": true,
                "_title": "battleroyalenewsv2",
                "header": "",
                "style": "None",
                "_noIndex": false,
                "alwaysShow": false,
                "jcr:baseVersion": "a7ca237317f1e704b1a186-6846-4eaa-a542-c2c8ca7e7f29",
                "_activeDate": "2020-01-21T14:00:00.000Z",
                "lastModified": "2020-11-01T17:36:19.024Z",
                "_locale": "en-US"
            },
            "Creativenewsv2": {
                "news": {
                    "motds": [{
                        "entryType": "Website",
                        "image": "https://cdn.discordapp.com/attachments/703974059121049720/715300713995042877/Fornite1920x1080.jpg",
                        "tileImage": "https://cdn.discordapp.com/attachments/703974059121049720/715300717837156362/FortniteMidLogo.jpg",
                        "videoMute": false,
                        "hidden": false,
                        "tabTitleOverride": "Neonite V2",
                        "_type": "CommonUI Simple Message MOTD",
                        "title": "Neonite",
                        "body": "Made by Kemo (@xkem0x). If you have any bugs, you can join our Discord by clicking the button below.",
                        "videoLoop": false,
                        "videoStreamingEnabled": false,
                        "sortingPriority": 80,
                        "id": "NeoniteNews",
                        "videoAutoplay": false,
                        "videoFullscreen": false,
                        "spotlight": false,
                        "websiteURL": "https://discord.gg/DJ6VUmD",
                        "websiteButtonText" : "Join our discord"
                    }
                ],
                },
                "jcr:isCheckedOut": true,
                "_title": "Creativenewsv2",
                "header": "",
                "style": "None",
                "_noIndex": false,
                "alwaysShow": false,
                "jcr:baseVersion": "a7ca237317f1e704b1a186-6846-4eaa-a542-c2c8ca7e7f29",
                "_activeDate": "2020-01-21T14:00:00.000Z",
                "lastModified": "2020-11-01T17:36:19.024Z",
                "_locale": "en-US"
            },
            "_suggestedPrefetch": []
        })
    })
}