module.exports = (app, port) => {
    app.get("/content/api/pages/fortnite-game", (req, res) => {
        res.json({
            "jcr:isCheckedOut": true,
            "_title": "Fortnite Game",
            "jcr:baseVersion": "a7ca237317f1e7b00bc82e-d9a2-4f0d-b951-704d295cd1aa",
            "_activeDate": "2017-07-24T22:24:02.300Z",
            "lastModified": "2020-11-01T17:36:19.024Z",
            "_locale": "en-US",
            "emergencynotice": {
                "news": {
                    "platform_messages": [],
                    "_type": "Battle Royale News",
                    "messages": [{
                        "hidden": false,
                        "_type": "CommonUI Simple Message Base",
                        "subgame": "br",
                        "body": "Created by Kemo (@xkem0x).\nForked by PogniteHQ (@pognitehq).",
                        "title": "PogniteNEO V1",
                        "spotlight": false
                    }, 
                    ],
                },
                "jcr:isCheckedOut": true,
                "_title": "emergencynotice",
                "_noIndex": false,
                "alwaysShow": true,
                "jcr:baseVersion": "a7ca237317f1e761d4ee60-7c40-45a8-aa3e-bb0a2ffa9bb5",
                "_activeDate": "2018-08-06T19:00:26.217Z",
                "lastModified": "2020-10-30T04:50:59.198Z",
                "_locale": "en-US"
            },
            "playlistinformation": {
                "is_tile_hidden": true,
                "frontend_matchmaking_header_style": "None",
                "conversion_config": {
                    "containerName": "playlist_info",
                    "_type": "Conversion Config",
                    "enableReferences": true,
                    "contentName": "playlists"
                },
                "jcr:isCheckedOut": true,
                "show_ad_violator": false,
                "_title": "playlistinformation",
                "frontend_matchmaking_header_text_description": "NOW AVAILABLE",
                "frontend_matchmaking_header_text": "NEW LTM!",
                "playlist_info": {
                    "_type": "Playlist Information",
                    "playlists": [{
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v12/partyroyaleupdated/EN_12PR_In-Game_Launch_ModeTile-1024x512-13cf734f07363d61f6fec3a2f5486a3550035c32.jpg",
                        "playlist_name": "Playlist_Papaya",
                        "hidden": false,
                        "violator": "",
                        "_type": "FortPlaylistInfo",
                        "description": "Welcome to Party Royale, a new experimental and evolving space. Leave your weapons and mats behind and hang out with friends, play games and enjoy live entertainment. Catch live shows. Race around obstacle courses by land or sea. Go fishing with friends, perfect your skydive, and get up close and connect with some of your favorite artists. Hop on the party bus and enjoy the ride."
                    },{
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10BR_ZoneWars_In-Game_ModeTile_Black-1024x512-23ba95e82931361ce535a643fdac54e120254374.jpg",
                        "playlist_name": "Playlist_Creative_ZebraWallet_V",
                        "violator": "PARTY FFA",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Code zeroyahero Vortex Zone Wars A party, FFA simulation of the end-game scenario in Battle Royale with a quick-moving zone. Eliminate the competition as you avoid the Storm. Randomized spawns and inventory items make each round unique. Stick around after the first game. There are multiple rounds in each session.  This island puts a unique twist on the Zone Wars game with mountainous terrain to traverse. The elevation change from zone to zone can be quite drastic!  Created by Zeroyahero",
                        "display_name": "Vortex"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10BR_TheCombine_ModeTile-1024x512-3aa8ebdfe1df7d9995e824a781eacdb954ee9615.jpg",
                        "playlist_name": "Playlist_Crucible_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/BR_LTM-Tile_Playground-1024x512-53db8a4b5fb41251af279eaf923bc00ecbc17792.jpg",
                        "playlist_name": "Playlist_Creative_PlayOnly_40",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/10CM_LTM_KnockTown_Playlist-1024x512-72e32b88b332b4d3ee3ee5255eff9522b660485c.jpg",
                        "playlist_name": "Playlist_Creative_KaleTofu",
                        "violator": "COMMUNITY CREATION",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Bounty_LTM_V2_Playlist_Tile-1024x512-3528a95d869a442d61687b52253a56a36c92eea3.jpg",
                        "playlist_name": "Playlist_Bounty_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Bounty_LTM_V2_Playlist_Tile-1024x512-3528a95d869a442d61687b52253a56a36c92eea3.jpg",
                        "playlist_name": "Playlist_Bounty_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Bounty_LTM_V2_Playlist_Tile-1024x512-3528a95d869a442d61687b52253a56a36c92eea3.jpg",
                        "playlist_name": "Playlist_Bounty_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/09CM_WorldCup_FeatIsland_WorldRun_ModeTile-1024x512-34d66c90603f4e64ebd56054b889c4ec163abea5.jpg",
                        "playlist_name": "Playlist_Creative_Squad_Battle_16_B",
                        "violator": "COMMUNITY CREATION",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_SneakySilencers-1024x512-1669e2eeddca63b61e9b94cc19c3ec502fd33f29.jpg",
                        "playlist_name": "Playlist_Sneaky_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/09CM_WorldCup_FeatIsland_JunkyardJuke_ModeTile-1024x512-7a2585ce248f1efa438674c368b37116dc5514de.jpg",
                        "playlist_name": "Playlist_Creative_Squad_Battle_16_A",
                        "violator": "COMMUNITY CREATION",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/09CM_WorldCup_FeatIsland_SkyStation_ModeTile-1024x512-a5424f9ac27626a73646c9fd158901c4c363ec0c.jpg",
                        "playlist_name": "Playlist_Creative_Squad_Battle_32_A",
                        "violator": "COMMUNITY CREATION",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Created by Team Evolve. Featured in the Fortnite World Cup Creative Finals.  Battle other squads to capture zones and score points! Any player can capture a zone and score points for your team. Use impulse grenades to blast other teams out of the capture zones. Players can now earn XP after each game and the top three teams will earn bonus XP."
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-oneshot-motd-1024x512-1024x512-347318026.jpg",
                        "playlist_name": "Playlist_Low_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_HeavyMetal_ModeTile-1024x512-4db8223707fb313220eef577dafde5c14106e49d.jpg",
                        "playlist_name": "Playlist_Heavy_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/09CM_In-Game_PropHunt_ModeTile-1024x512-1510311027a93a720b42ed22e711c7e478931adb.jpg",
                        "playlist_name": "Playlist_Creative_PuppyHugs",
                        "violator": "PLAYER MADE!",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Unvaulted-1024x512-d3cbe3c4a756190279af4ce98773d6599f7aab4f.jpg",
                        "playlist_name": "Playlist_Unvaulted_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/EN_CM09_BeachAssaultCreativeLTM_ContestWinner_ModeTile-1024x512-9cdeb2e0ea37179a37d3384cf73c9949d2d19546.jpg",
                        "playlist_name": "Playlist_Creative_BeachAssault",
                        "violator": "PLAYER MADE",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": "BEACH ASSAULT BY PRUDIZ"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Barebones-1024x512-4a29337febb04e9043d57c9e61afe849f8a9e9c7.jpg",
                        "playlist_name": "Playlist_Hard_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "This mode has the map, compass, storm timer and many other elements of the Heads Up Display turned off."
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_BlueWeapons_ModeTile-1024x512-0c38f1bc3b991943e3f6650bf7acfbcdd8739b1e.jpg",
                        "playlist_name": "Playlist_Blue_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Solid_Gold_Playlist_Tile_1025x512-1024x512-ea1253854e55ed01f3d6e012ecfa373cc1b38d37.jpg",
                        "playlist_name": "Playlist_SolidGold_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_PurpleReign_ModeTile-1024x512-c5a7e2bd3f32b83f17e4fa28817312ab6210133c.jpg",
                        "playlist_name": "Playlist_Purple_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_FullAuto_ModeTile-1024x512-d1532221d738ba3aed434512b7c670e72b89f474.jpg",
                        "playlist_name": "Playlist_Auto_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_HeavyMetal_ModeTile-1024x512-4db8223707fb313220eef577dafde5c14106e49d.jpg",
                        "playlist_name": "Playlist_Heavy_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-gungame-motd-1024x512-1024x512-501005598.jpg",
                        "playlist_name": "Playlist_Gungame_Reverse",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_Surfin_ModeTile-1024x512-ebff23e30b121cfe3eecf173949c055325522090.jpg",
                        "playlist_name": "Playlist_Race_12",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_DeaglesandHeadshots_ModeTile-1024x512-4d969f5a9126ba71b7ee77088fd22df5b4c7caba.jpg",
                        "playlist_name": "Playlist_Beagles_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_LeaveNoneBehind_ModeTile-1024x512-bfe65d02a5d42577d22c133d25ad9c9fb62a35a0.jpg",
                        "playlist_name": "Playlist_Behind_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_LoadoutSwap_ModeTile-1024x512-f73c146f8ccc7998aab14f8c1957f0ad01faa933.jpg",
                        "playlist_name": "Playlist_Swap_Squads_Respawn",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_TankBattle_ModeTile-1024x512-48554aae511d9c5a7ac1a5d4fd54e0f5a37bd66d.jpg",
                        "playlist_name": "Playlist_Tank_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_StrategicStructures_ModeTile-1024x512-4f6f448375284fef60fe2a2c15f292115ebec558.jpg",
                        "playlist_name": "Playlist_Strategic_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_BuildersParadise_ModeTile-1024x512-730a5ffe51c8f0420b91529d1fc05e081aa2071c.jpg",
                        "playlist_name": "Playlist_Paradise_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_PowerUp_ModeTile-1024x512-7e1824071133f9eac4ca44c701605923893c85bf.jpg",
                        "playlist_name": "Playlist_Pow_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_BuilttoLast_ModeTile-1024x512-cf95f4701f41c608ae8590fe588a5a0ea25ed68a.jpg",
                        "playlist_name": "Playlist_Care_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_Tag_ModeTile-1024x512-d4471981ccdc8d9f444d1f416b3f4458612da006.jpg",
                        "playlist_name": "Playlist_Tag_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_SiphonRumble_ModeTile-1024x512-02ad3c97e4cdc7172f6ea59140b89b004f95886a.jpg",
                        "playlist_name": "Playlist_Respawn_20_Sif",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/14DaysofSummer/09BR_14DoS_LTM_LavaRumble_ModeTile-1024x512-29cc6ad680519d8f792bf1fa4053cf9191f84b6e.jpg",
                        "playlist_name": "Playlist_Respawn_20_Lava",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-payback-motd-1024x512-1024x512-500823017.jpg",
                        "playlist_name": "Playlist_Respawn_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/09BR_LTM_HordeRush_Mode_Tile-1024x512-a844840eb58db868b6abfbe18fc8a8f483e18c60.jpg",
                        "playlist_name": "Playlist_Mash_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/09BR_LTM_DowntownDrop_Screenshot_ModeTile-1024x512-d8ce0a16ae59e2a2f501813ddf540a00e60098b5.jpg",
                        "playlist_name": "Playlist_Creative_Vigilante",
                        "violator": "PLAYER MADE!",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Created by NotNellaf & Tollmolia in collaboration with Jordan Brand. "
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/09BR_Social_LTM_WicksBounty_Announce_PlaylistTile-1024x512-df3870c355530a7591c7a3fa453c15686c862989.jpg",
                        "playlist_name": "Playlist_Wax_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/09BR_Social_LTM_WicksBounty_Announce_PlaylistTile-1024x512-df3870c355530a7591c7a3fa453c15686c862989.jpg",
                        "playlist_name": "Playlist_Wax_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/09BR_Social_LTM_WicksBounty_Announce_PlaylistTile-1024x512-df3870c355530a7591c7a3fa453c15686c862989.jpg",
                        "playlist_name": "Playlist_Wax_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_Endgame_InGame_Mode-Tile-1024x512-03bb0dc121ae8b2dcd27b8b386670737093d0c83.jpg",
                        "playlist_name": "Playlist_Ashton_Sm",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/EN_08BR_DeepFried_Mode_Tile-1024x512-227979fa27053f858066a1a47d68b55f792fded1.jpg",
                        "playlist_name": "Playlist_Barrier_16_B_Lava",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_AirRoyale_Mode-Tile-1024x512-e071f542b7e0ce2cfc34c208e14604815b76439c.jpg",
                        "playlist_name": "Playlist_Goose_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_AirRoyale_Mode-Tile-1024x512-e071f542b7e0ce2cfc34c208e14604815b76439c.jpg",
                        "playlist_name": "Playlist_Goose_Duos_24",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_AirRoyale_Mode-Tile-1024x512-e071f542b7e0ce2cfc34c208e14604815b76439c.jpg",
                        "playlist_name": "Playlist_Goose_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/CM_LobbyTileArt-1024x512-fbcd48db36552ccb1ab4021b722ea29d515377cc.jpg",
                        "playlist_name": "Playlist_PlaygroundV2",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "Play the best games made by the community. There is a new Featured Island to check out every day!"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_FloorIsLava_ModeTile-1024x512-f1af4cd98c7ff0ce4058f4e3b65a853641d0a35e.jpg",
                        "playlist_name": "Playlist_Fill_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_FloorIsLava_ModeTile-1024x512-f1af4cd98c7ff0ce4058f4e3b65a853641d0a35e.jpg",
                        "playlist_name": "Playlist_Fill_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_FloorIsLava_ModeTile-1024x512-f1af4cd98c7ff0ce4058f4e3b65a853641d0a35e.jpg",
                        "playlist_name": "Playlist_Fill_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_SolidGreen_ModeTile_Squads-1024x512-f0d931472907d54ffaa52ef81f78bf9d5fcfaa2d.jpg",
                        "playlist_name": "Playlist_Green_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_SolidGreen_ModeTile_Squads-1024x512-f0d931472907d54ffaa52ef81f78bf9d5fcfaa2d.jpg",
                        "playlist_name": "Playlist_Green_Squad",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_LTM_SolidGreen_ModeTile_Squads-1024x512-f0d931472907d54ffaa52ef81f78bf9d5fcfaa2d.jpg",
                        "playlist_name": "Playlist_Green_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_WinterFest_Social_Slide_LTM_MOTD_1024x512-1024x512-e568425bdc8ac88c7cea6a277d0cf3f081563541.jpg",
                        "playlist_name": "Playlist_Slide_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Unvaulted-1024x512-d3cbe3c4a756190279af4ce98773d6599f7aab4f.jpg",
                        "playlist_name": "Playlist_Classic_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_Drifting50s_Powder-1024x512-5fb24cfd4d83e4cd3a3589b126313beba9cc69a7.jpg",
                        "playlist_name": "Playlist_Hover",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_Drifting50s_Powder-1024x512-5fb24cfd4d83e4cd3a3589b126313beba9cc69a7.jpg",
                        "playlist_name": "Playlist_Hover_64",
                        "violator": "Large Team Mode",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_Drifting50s_Powder-1024x512-5fb24cfd4d83e4cd3a3589b126313beba9cc69a7.jpg",
                        "playlist_name": "Playlist_Hover_48",
                        "violator": "Large Team Mode",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_InfinityBlade_v2-1024x512-475608c25c288f7d5c884eeebc47fb565f6f5803.jpg",
                        "playlist_name": "Playlist_Sword_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_InfinityBlade_v2-1024x512-475608c25c288f7d5c884eeebc47fb565f6f5803.jpg",
                        "playlist_name": "Playlist_Sword_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_InfinityBlade_v2-1024x512-475608c25c288f7d5c884eeebc47fb565f6f5803.jpg",
                        "playlist_name": "Playlist_Sword_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_LoveShot_v2-1024x512-cd7b917157be2472bebc3db3b125e9b20174c748.jpg",
                        "playlist_name": "Playlist_Love_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_LoveShot_v2-1024x512-cd7b917157be2472bebc3db3b125e9b20174c748.jpg",
                        "playlist_name": "Playlist_Love_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_LoveShot_v2-1024x512-cd7b917157be2472bebc3db3b125e9b20174c748.jpg",
                        "playlist_name": "Playlist_Love_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Catch_LTM_ModeTile_1024x512-1024x512-c082fbf692a53d713da02592e9de69faeefd587c.jpg",
                        "playlist_name": "Playlist_Toss_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_LTM_CatchSquads-1024x512-7289222d56b08ef8de20c7187af2670496dca3df.jpg",
                        "playlist_name": "Playlist_Toss_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-catch-motd-1024x512-1024x512-500636478.jpg",
                        "playlist_name": "Playlist_Toss_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_NFL_Playlist_Tile-1024x512-767f5e54a71ef1c9fbd4bfdb8c8ec3b15aac8a5e.jpg",
                        "playlist_name": "Playlist_Omaha",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_WinterDeimos_Squads-1024x512-cf4323aa9c2cfd027484cf4da14544128e3d4c7e.jpg",
                        "playlist_name": "Playlist_Deimos_Squad_Winter",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_WinterDeimos_Duos_-1024x512-84315aac8d1fcfb840deba46c4dafda8e9005b2a.jpg",
                        "playlist_name": "Playlist_Deimos_Duo_Winter",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_ModeTile_WinterDeimos_Solo-1024x512-5c759fe60ec85988f35c729b5fb6a7993d8dbb58.jpg",
                        "playlist_name": "Playlist_Deimos_Solo_Winter",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-oneshot-motd-1024x512-1024x512-347318026.jpg",
                        "playlist_name": "Playlist_Low_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_GroundGame-1024x512-37a4d1d335b4c9427bdc672db0f335f4df813874.jpg",
                        "playlist_name": "Playlist_Ground_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_WildWest-1024x512-42779242a5a73d654332d9d0afe0983f9d8401d0.jpg",
                        "playlist_name": "Playlist_WW_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Slide-1024x512-189625349e80dc81e225691aa952ffd280996058.jpg",
                        "playlist_name": "Playlist_Slide_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_GroundGame-1024x512-37a4d1d335b4c9427bdc672db0f335f4df813874.jpg",
                        "playlist_name": "Playlist_Ground_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_GroundGame-1024x512-37a4d1d335b4c9427bdc672db0f335f4df813874.jpg",
                        "playlist_name": "Ground_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-oneshot-motd-1024x512-1024x512-347318026.jpg",
                        "playlist_name": "Playlist_Low_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_HighExplosives50s-1024x512-3a8d44af3c2718b5aaaaebbd4627258a657bf0bf.jpg",
                        "playlist_name": "Playlist_50v50HE",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_HighExplosives-1024x512-4afc4219531db710e56f3b038e7cd84ca2be7675.jpg",
                        "playlist_name": "Playlist_HighExplosives_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_HighExplosives-1024x512-4afc4219531db710e56f3b038e7cd84ca2be7675.jpg",
                        "playlist_name": "Playlist_HighExplosives_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_HighExplosives-1024x512-4afc4219531db710e56f3b038e7cd84ca2be7675.jpg",
                        "playlist_name": "Playlist_HighExplosives_Squads / Event 24",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_WildWest-1024x512-42779242a5a73d654332d9d0afe0983f9d8401d0.jpg",
                        "playlist_name": "Playlist_WW_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_SneakySilencers-1024x512-1669e2eeddca63b61e9b94cc19c3ec502fd33f29.jpg",
                        "playlist_name": "Playlist_Sneaky_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_FoodFight16-1024x512-309538a1b961b5ab0c22417ab34170cc302bbab8.jpg",
                        "playlist_name": "Playlist_Barrier_16",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_CloseEncounters50s-1024x512-03dcc058e1bec3e853b3ee20594128805223b5a3.jpg",
                        "playlist_name": "Playlist_Close_50",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_HolidayDisco-1024x512-684bd4b41613e59d895a477389515a8b4878da6a.jpg",
                        "playlist_name": "Playlist_Disco_32_Alt",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Slide-1024x512-189625349e80dc81e225691aa952ffd280996058.jpg",
                        "playlist_name": "Playlist_Slide_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Barebones-1024x512-4a29337febb04e9043d57c9e61afe849f8a9e9c7.jpg",
                        "playlist_name": "Playlist_Hard_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/13br-summersplash-ltm-siphon-motd-1024x512-1024x512-501004672.jpg",
                        "playlist_name": "Playlist_Vamp_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR07_14-DoF_Social-1024x512-5fa7dd4752d1f0cc1a101f09cb170d0f5b2a31cf.jpg",
                        "playlist_name": "Playlist_33",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR_LTM_Unvaulted-1024x512-d3cbe3c4a756190279af4ce98773d6599f7aab4f.jpg",
                        "playlist_name": "Playlist_Unvaulted_Squads",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/team-rumble-1024x512-534456830.jpg",
                        "playlist_name": "Playlist_Respawn_24",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_ModeTile_LTM_WildWest-1024x512-f67d9d1dd2ca0b290c92b1380240429f0f257a10.jpg",
                        "playlist_name": "Playlist_WW_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_LobbyTile_FoodFight-1024x512-5e1540a0a2ba0a1f663d32c60cfec3a360278672.png",
                        "playlist_name": "Playlist_Barrier_12",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_In-GamePlaylist_TeamTerror-1024x512-310430bdaf1b1dd0ecb4d3b180bb6409b7ff6e27.jpg",
                        "playlist_name": "playlist_deimos_50",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "description": "",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_Fortnitemares_In-GamePlaylist_1024x512_-Solo-1024x512-7e7fe76e48beb3a06da0592cb26e412265986e4d.jpg",
                        "playlist_name": "Playlist_Deimos_Solo",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_Fortnitemares_In-GamePlaylist_1024x512_Squads-1024x512-783a0812f6acf1f5931c8015e6ad13c0b76c5a9c.jpg",
                        "playlist_name": "Playlist_Deimos_Squad",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_Fortnitemares_In-GamePlaylist_1024x512_Duos-1024x512-1eadb7cfab62c9eb5c90c65577c676d5d0bb15c2.jpg",
                        "playlist_name": "Playlist_Deimos_Duo",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo",
                        "display_name": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_LobbyTile_LTM_DiscoDomination-1024x512-c79f07de78d8283656fcf4d1ee757f880911d775.jpg",
                        "playlist_name": "Playlist_Disco_32",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR06_LobbyTile_LTM_DiscoDomination-1024x512-c79f07de78d8283656fcf4d1ee757f880911d775.jpg",
                        "playlist_name": "Playlist_Disco",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_Soaring50s-1024x512-80762dcc260cc959c11dac2ca2f6ae176eb63ef3.jpg",
                        "playlist_name": "Playlist_Soaring_Squads",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_Soaring50s-1024x512-80762dcc260cc959c11dac2ca2f6ae176eb63ef3.jpg",
                        "playlist_name": "Playlist_Soaring_Duos",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_Soaring50s-1024x512-80762dcc260cc959c11dac2ca2f6ae176eb63ef3.jpg",
                        "playlist_name": "Playlist_Soaring_Solo",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_HighStakes_ModeTile-1024x512-741e576e8ae2e30c256ff3508011760ace890711.jpg",
                        "playlist_name": "Playlist_Bling_Squads",
                        "violator": "",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_HighStakes_ModeTile-1024x512-741e576e8ae2e30c256ff3508011760ace890711.jpg",
                        "playlist_name": "Playlist_Bling_Duos",
                        "violator": "",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo",
                        "description": ""
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/08BR_HighStakes_ModeTile-1024x512-741e576e8ae2e30c256ff3508011760ace890711.jpg",
                        "playlist_name": "Playlist_Bling_Solo",
                        "violator": "",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Solid_Gold_Playlist_Tile_1025x512-1024x512-ea1253854e55ed01f3d6e012ecfa373cc1b38d37.jpg",
                        "playlist_name": "Playlist_50v50SAU",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM_ScoreRoyale-1024x512-b608aaf7840cdf6b7a702c5cbe1848a2247516d6.jpg",
                        "playlist_name": "Playlist_Score_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM_ScoreRoyale-1024x512-b608aaf7840cdf6b7a702c5cbe1848a2247516d6.jpg",
                        "playlist_name": "Playlist_Score_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM_ScoreRoyale-1024x512-b608aaf7840cdf6b7a702c5cbe1848a2247516d6.jpg",
                        "playlist_name": "Playlist_Score_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_Soaring50s-1024x512-80762dcc260cc959c11dac2ca2f6ae176eb63ef3.jpg",
                        "playlist_name": "Playlist_Soaring_50s",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM-Steady-Storm-1024x512-f38e603ed9c80b6210a25c4737d3d8b675b8d28e.jpg",
                        "playlist_name": "Playlist_Steady_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM-Steady-Storm-1024x512-f38e603ed9c80b6210a25c4737d3d8b675b8d28e.jpg",
                        "playlist_name": "Playlist_Steady_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LobbyTile_LTM-Steady-Storm-1024x512-f38e603ed9c80b6210a25c4737d3d8b675b8d28e.jpg",
                        "playlist_name": "Playlist_Steady_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_FlyExplosives-1024x512-6283e3392b3aa44794dac64423b22606f8773503.png",
                        "playlist_name": "Playlist_FlyExplosives_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_FlyExplosives-1024x512-6283e3392b3aa44794dac64423b22606f8773503.png",
                        "playlist_name": "Playlist_FlyExplosives_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR05_LTM_FlyExplosives-1024x512-6283e3392b3aa44794dac64423b22606f8773503.png",
                        "playlist_name": "Playlist_FlyExplosives_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/LTM_Tile_FinalFight-1024x576-5af82788940faeef422ad204aaa241e36e7c9c56.jpg",
                        "playlist_name": "Playlist_Final_12",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/BR_LTM-Tile_Playground-1024x512-53db8a4b5fb41251af279eaf923bc00ecbc17792.jpg",
                        "playlist_name": "Playlist_Creative_PlayOnly",
                        "violator": "",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo",
                        "display_subname": "-"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistimages/BR_LTM-Tile_Tactics-Showdown-1024x512-a84753f49eb70d8751a99b4db83cdb5eb8290166.jpg",
                        "playlist_name": "Playlist_Taxes_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistimages/BR_LTM-Tile_Tactics-Showdown-1024x512-a84753f49eb70d8751a99b4db83cdb5eb8290166.jpg",
                        "playlist_name": "Playlist_Taxes_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistimages/BR_LTM-Tile_Tactics-Showdown-1024x512-a84753f49eb70d8751a99b4db83cdb5eb8290166.jpg",
                        "playlist_name": "Playlist_Taxes_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/LTM_Tile_FinalFight-1024x576-5af82788940faeef422ad204aaa241e36e7c9c56.jpg",
                        "playlist_name": "Playlist_Final_20",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR04_LTM_SniperShootout-1024x512-bcaf8004961e4e374d0603813f840f4b575d230b.jpg",
                        "playlist_name": "Playlist_Snipers_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR04_LTM_SniperShootout-1024x512-bcaf8004961e4e374d0603813f840f4b575d230b.jpg",
                        "playlist_name": "Playlist_Snipers_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR04_LTM_SniperShootout-1024x512-bcaf8004961e4e374d0603813f840f4b575d230b.jpg",
                        "playlist_name": "Playlist_Snipers_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/BR04_LTM_BlitzShowdown-1024x512-7eccbc505214ac522cc5dde7b3ceaa3a5f99e754.png",
                        "playlist_name": "Playlist_Comp_Blitz_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR04_LTM_5x20-1024x512-451b402db5751c25a1e7616930c5ae37d8b20710.png",
                        "playlist_name": "Playlist_5x20",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_In-Game_LTM_Blitz_Masked_ModeTile-1024x512-ca1788d0b956e789da358481747272e1bb64c710.jpg",
                        "playlist_name": "Playlist_Blitz_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_In-Game_LTM_Blitz_Masked_ModeTile-1024x512-ca1788d0b956e789da358481747272e1bb64c710.jpg",
                        "playlist_name": "Playlist_Blitz_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_In-Game_LTM_Blitz_Masked_ModeTile-1024x512-ca1788d0b956e789da358481747272e1bb64c710.jpg",
                        "playlist_name": "Playlist_Blitz_Squad",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Close_EncountersMOTD_1024x512-1024x512-b8ae46224a1de0d4db833c23755f4afabffb34b9.jpg",
                        "playlist_name": "Playlist_Close_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Close_EncountersMOTD_1024x512-1024x512-b8ae46224a1de0d4db833c23755f4afabffb34b9.jpg",
                        "playlist_name": "Playlist_Close_Squads",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Close_EncountersMOTD_1024x512-1024x512-b8ae46224a1de0d4db833c23755f4afabffb34b9.jpg",
                        "playlist_name": "Playlist_Close_Duos",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/BR04_LTM_SoloShowdown-1024x512-0f522b0881adebfe241c6527f03c9140f70b88a7.png",
                        "playlist_name": "Playlist_Comp_Solo",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/v94/11BR_Solid_Gold_Playlist_Tile_1025x512-1024x512-ea1253854e55ed01f3d6e012ecfa373cc1b38d37.jpg",
                        "playlist_name": "Playlist_SolidGold_Solo",
                        "violator": "",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlisttiles/LTM_50v50-1024x512-788bf1a67426f54307c4296123ac2d3ff8cc0d6c.png",
                        "playlist_name": "Playlist_50v50",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/Fortnite/fortnite-game/playlistinformation/BR04_LTM_Gauntlet-1024x512-a0dca279534a121957275bcdb0b42042d8a010fd.png",
                        "playlist_name": "Playlist_Carmine",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-launch-modetiles-solo-1024x512-850175411.jpg",
                        "playlist_name": "Playlist_DefaultSolo",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-fortnitemares-solo-1024x512-326832464.jpg",
                        "playlist_name": "Playlist_Arseniccore_Solo_Maxfog",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-fortnitemares-duos-1024x512-326842571.jpg",
                        "playlist_name": "Playlist_DefaultDuo",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-fortnitemares-duos-1024x512-326842571.jpg",
                        "playlist_name": "Playlist_Arseniccore_Duos_Maxfog",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-launch-modetiles-trios-1024x512-850175437.jpg",
                        "playlist_name": "playlist_trios",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-fortnitemares-trios-1024x512-326846465.jpg",
                        "playlist_name": "playlist_arseniccore_trios_maxfog",
                        "hidden": false,
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-launch-modetiles-squad-1024x512-850175426.jpg",
                        "playlist_name": "Playlist_DefaultSquad",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }, {
                        "image": "https://cdn2.unrealengine.com/14br-fortnitemares-squad-1024x512-326850231.jpg",
                        "playlist_name": "playlist_arseniccore_squads_maxfog",
                        "hidden": false,
                        "special_border": "None",
                        "_type": "FortPlaylistInfo"
                    }]
                },
                "_noIndex": false,
                "jcr:baseVersion": "a7ca237317f1e7e358ae2f-0f54-4e20-8ec7-267b4668393c",
                "_activeDate": "2018-04-25T15:05:39.956Z",
                "lastModified": "2020-10-16T11:57:44.884Z",
                "_locale": "en-US"
            },
            "dynamicbackgrounds": {
                "jcr:isCheckedOut": true,
                "backgrounds": {
                    "backgrounds": [{
                        "stage": "season15",
                        "_type": "DynamicBackground",
                        "key": "lobby"
                    }, {
                        "stage": "season15",
                        "_type": "DynamicBackground",
                        "key": "vault"
                    }],
                    "_type": "DynamicBackgroundList"
                },
                "_title": "dynamicbackgrounds",
                "_noIndex": false,
                "jcr:baseVersion": "a7ca237317f1e7bac3355e-3ec1-4054-baf5-f88613799961",
                "_activeDate": "2019-08-21T15:59:59.342Z",
                "lastModified": "2020-08-27T08:04:47.051Z",
                "_locale": "en-US"
            },
            "athenamessage": {
                "_title": "athenamessage",
                "overrideablemessage": {
                    "_type": "CommonUI Simple Message",
                    "message": {
                        "_type": "CommonUI Simple Message Base",
                        "title": "PogniteNEO V1",
                        "body": "Created by Kemo (@xkem0x).\nForked by PogniteHQ (@pognitehq)."
                    }
                },
                "_activeDate": "2017-08-30T03:08:31.687Z",
                "lastModified": "2017-09-26T16:20:19.191Z",
                "_locale": "en-US"
            },
            "savetheworldnews": {
                "news": {
                    "_type": "Battle Royale News",
                    "messages": [{
                        "image": `http://127.0.0.1:${port}/PogniteNeoWallpaper1024x546.png`,
                        "hidden": false,
                        "_type": "CommonUI Simple Message Base",
                        "adspace": "PogniteNEO V1",
                        "title": "PogniteNEO",
                        "body": "Created by Kemo (@xkem0x).\nForked by PogniteHQ (@pognitehq).",
                        "spotlight": false
                    }]
                },
                "jcr:isCheckedOut": true,
                "_title": "SaveTheWorldNews",
                "_noIndex": false,
                "alwaysShow": true,
                "jcr:baseVersion": "a7ca237317f1e79a6efa59-3f42-4a68-a8c7-cb2e21ec462c",
                "_activeDate": "2020-01-22T00:00:00.000Z",
                "lastModified": "2020-09-25T16:41:01.892Z",
                "_locale": "en-US"
            },
            "loginmessage": {
                "_title": "Message de connexion",
                "loginmessage": {
                    "_type": "CommonUI Simple Message",
                    "message": {
                        "_type": "CommonUI Simple Message Base",
                        "title": "PogniteNEO",
                        "body": "Created by Kemo (@xkem0x).\nForked by PogniteHQ (@pognitehq)."
                    }
                },
                "_activeDate": "2017-07-19T13:14:04.490Z",
                "lastModified": "2018-03-15T07:10:53.113Z",
                "_locale": "en-US"
            },
            "shopSections": {
                "jcr:isCheckedOut": true,
                "_title": "shop-sections",
                "sectionList": {
                    "_type": "ShopSectionList",
                    "sections": [{
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 70,
                        "sectionId": "Featured",
                        "bShowTimer": true,
                        "sectionDisplayName": "Featured",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 69,
                        "sectionId": "Featured2",
                        "bShowTimer": false,
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 65,
                        "sectionId": "CustomizeHero",
                        "bShowTimer": true,
                        "sectionDisplayName": "Customize Your Hero!",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 64,
                        "sectionId": "HeroGear",
                        "bShowTimer": true,
                        "sectionDisplayName": "Hero Gear",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": false,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 65,
                        "sectionId": "BannerBrigade",
                        "bShowTimer": true,
                        "sectionDisplayName": "Banner Brigade",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 64,
                        "sectionId": "BannerGear",
                        "bShowTimer": true,
                        "sectionDisplayName": "Banner Gear",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 60,
                        "sectionId": "Daily",
                        "bShowTimer": true,
                        "sectionDisplayName": "Daily",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 59,
                        "sectionId": "Daily2",
                        "bShowTimer": true,
                        "sectionDisplayName": "",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 60,
                        "sectionId": "Special",
                        "bShowTimer": true,
                        "sectionDisplayName": "Special Offers",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 59,
                        "sectionId": "Special2",
                        "bShowTimer": true,
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 65,
                        "sectionId": "StarWars",
                        "bShowTimer": true,
                        "sectionDisplayName": "Star Wars",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 65,
                        "sectionId": "StartParty",
                        "bShowTimer": true,
                        "sectionDisplayName": "Start the Party!",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 64,
                        "sectionId": "PartyGear",
                        "bShowTimer": true,
                        "sectionDisplayName": "Party Gear",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 64,
                        "sectionId": "TurnMusicUp",
                        "bShowTimer": true,
                        "sectionDisplayName": "Turn the Music Up!",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 30,
                        "sectionId": "SpookyOffers",
                        "bShowTimer": true,
                        "sectionDisplayName": "Spooky Offers",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 29,
                        "sectionId": "SpookyOffers2",
                        "bShowTimer": true,
                        "sectionDisplayName": "",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 65,
                        "sectionId": "Fortnitemares",
                        "bShowTimer": true,
                        "sectionDisplayName": "Fortnitemares",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 65,
                        "sectionId": "Ghostbusters",
                        "bShowTimer": true,
                        "sectionDisplayName": "Ghostbusters",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 64,
                        "sectionId": "GhostbustersGear",
                        "bShowTimer": true,
                        "sectionDisplayName": "Ghostbusters Gear",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 40,
                        "sectionId": "Marvel",
                        "bShowTimer": true,
                        "sectionDisplayName": "Marvel",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 39,
                        "sectionId": "Marvel2",
                        "bShowTimer": true,
                        "sectionDisplayName": "",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 38,
                        "sectionId": "Marvel3",
                        "bShowTimer": true,
                        "sectionDisplayName": "",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "_type": "DynamicBackground"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 37,
                        "sectionId": "Marvel4",
                        "bShowTimer": true,
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "sectionId": "Bundles",
                        "bShowTimer": true,
                        "sectionDisplayName": "Bundles",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "sectionId": "Characters",
                        "bShowTimer": true,
                        "sectionDisplayName": "Outfits",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "sectionId": "Backpacks",
                        "bShowTimer": true,
                        "sectionDisplayName": "Back Blings",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 0,
                        "sectionId": "Pickaxes",
                        "bShowTimer": true,
                        "sectionDisplayName": "Harvesting Tools",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "sectionId": "Gliders",
                        "bShowTimer": true,
                        "sectionDisplayName": "Gliders",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "sectionId": "MusicPacks",
                        "bShowTimer": true,
                        "sectionDisplayName": "Music Packs",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "sectionId": "Wraps",
                        "bShowTimer": true,
                        "sectionDisplayName": "Wraps",
                        "bShowIneligibleOffers": true
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": true,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 80,
                        "sectionId": "LimitedTime",
                        "bShowTimer": false,
                        "sectionDisplayName": "Limited Time",
                        "bShowIneligibleOffers": false
                    }, {
                        "bSortOffersByOwnership": false,
                        "bShowIneligibleOffersIfGiftable": false,
                        "bEnableToastNotification": false,
                        "background": {
                            "stage": "default",
                            "_type": "DynamicBackground",
                            "key": "vault"
                        },
                        "_type": "ShopSection",
                        "landingPriority": 90,
                        "sectionId": "Battlepass",
                        "bShowTimer": false,
                        "sectionDisplayName": "Battle Pass",
                        "bShowIneligibleOffers": true
                    }]
                },
                "_noIndex": false,
                "jcr:baseVersion": "a7ca237317f1e77f7abaac-2b4d-4df8-828b-6056a1904470",
                "_activeDate": "2020-10-28T00:00:00.000Z",
                "lastModified": "2020-11-02T15:56:44.648Z",
                "_locale": "en-US"
            },
            "battleroyalenewsv2": {
                "news": {
                    "motds": [{
                        "entryType": "Website",
                        "image": `http://127.0.0.1:${port}/PogniteWallpaper1920x1080.png`,
                        "tileImage": `http://127.0.0.1:${port}/PogniteNeoWallpaper1024x546.png`,
                        "videoMute": false,
                        "hidden": false,
                        "tabTitleOverride": "PogniteNEO V1",
                        "_type": "CommonUI Simple Message MOTD",
                        "title": "PogniteNEO",
                        "body": "Created by Kemo (@xkem0x).\nForked by PogniteHQ (@pognitehq).",
                        "videoLoop": false,
                        "videoStreamingEnabled": false,
                        "sortingPriority": 80,
                        "id": "PogniteNEONewsBR",
                        "videoAutoplay": false,
                        "videoFullscreen": false,
                        "spotlight": false,
                        "websiteURL": "https://discord.gg/DJ6VUmD",
                        "websiteButtonTex" : "Join our discord"
                    }
                ],
                },
                "jcr:isCheckedOut": true,
                "_title": "battleroyalenewsv2",
                "header": "",
                "style": "None",
                "_noIndex": false,
                "alwaysShow": false,
                "jcr:baseVersion": "a7ca237317f1e704b1a186-6846-4eaa-a542-c2c8ca7e7f29",
                "_activeDate": "2020-01-21T14:00:00.000Z",
                "lastModified": "2020-11-01T17:36:19.024Z",
                "_locale": "en-US"
            },
            "Creativenewsv2": {
                "news": {
                    "motds": [{
                        "entryType": "Website",
                        "image": `http://127.0.0.1:${port}/PogniteNeoWallpaper1024x546.png`,
                        "tileImage": `http://127.0.0.1:${port}/PogniteNeoWallpaper1920x1080.png`,
                        "videoMute": false,
                        "hidden": false,
                        "tabTitleOverride": "PogniteNEO V1",
                        "_type": "CommonUI Simple Message MOTD",
                        "title": "PogniteNEO",
                        "body": "Created by Kemo (@xkem0x).\nForked by PogniteHQ (@pognitehq).",
                        "videoLoop": false,
                        "videoStreamingEnabled": false,
                        "sortingPriority": 80,
                        "id": "PogniteNEONews",
                        "videoAutoplay": false,
                        "videoFullscreen": false,
                        "spotlight": false,
                        "websiteURL": "https://discord.gg/DJ6VUmD",
                        "websiteButtonTex" : "Join our discord"
                    }
                ],
                },
                "jcr:isCheckedOut": true,
                "_title": "Creativenewsv2",
                "header": "",
                "style": "None",
                "_noIndex": false,
                "alwaysShow": false,
                "jcr:baseVersion": "a7ca237317f1e704b1a186-6846-4eaa-a542-c2c8ca7e7f29",
                "_activeDate": "2020-01-21T14:00:00.000Z",
                "lastModified": "2020-11-01T17:36:19.024Z",
                "_locale": "en-US"
            },
            "shopCarousel": {
                "jcr:isCheckedOut": true,
                "itemsList": {
                    "_type": "ShopCarouselItemList",
                    "items": [{
                        "tileImage": `http://127.0.0.1:${port}/PogniteNeoWallpaper1920x1080.png`,
                        "fullTitle": "PogniteNEO",
                        "hidden": false,
                        "_type": "ShopCarouselItem",
                        "landingPriority": 100,
                        "action": "ShowOfferDetails",
                        "offerId": "v2:/cc29bec6d0bdd2876fb412cf674a7960003bbb76b2eb9b930833a61b604a3b4e",
                        "title": "PogniteNEO"
                    }]
                },
                "_title": "shop-carousel",
                "_noIndex": false,
                "jcr:baseVersion": "a7ca237317f1e76d4c1405-e84c-4ece-bc50-7112ba557b33",
                "_activeDate": "2020-09-25T12:00:00.000Z",
                "lastModified": "2020-10-26T15:37:05.775Z",
                "_locale": "en-US"
            },
            "_suggestedPrefetch": []
        })
    })
}